# ============================================
# RompGPS Backend Configuration
# ============================================
spring.application.name=rompgps-backend
server.port=8081

# ============================================
# PostgreSQL - Usuarios (Autenticación)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/rompgps_users
spring.datasource.username=rompgps
spring.datasource.password=gps12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ============================================
# MongoDB - Datos GPS
# ============================================
spring.mongodb.uri=mongodb+srv://romp-gps:gps12345@gps-romp.qrz6ti5.mongodb.net/?appName=GPS-ROMP
spring.mongodb.database=Romp_Gps

# ============================================

spring.data.redis.host=localhost
spring.data.redis.port=6379
#============================================= CORS Configuration


# ============================================
# JWT
# ============================================
jwt.secreto=rompgps-clave-super-secreta-256-bits-minimo!!
jwt.expiracion=86400000

# ============================================
# Google OAuth2
# ============================================
google.client-id=426121822210-mjnojj5qmht0r8lmkfogfa7mc3ev4lrk.apps.googleusercontent.com

# ============================================
# GitHub OAuth2
# ============================================
github.client-id=Ov23lifcAXEVo4WKXu28
github.client-secret=be5546ceb909922c8ecc44b2bb3c993e3a6203a0
