# ============================================
# RompGPS Backend Configuration
# ============================================
spring.application.name=rompgps-backend
server.port=8081

# ============================================
# PostgreSQL - Usuarios (Autenticación)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/rompgps_users
spring.datasource.username=postgres
spring.datasource.password=123456h
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ============================================
# MongoDB - Datos GPS
# ============================================
spring.mongodb.uri=mongodb://localhost:27017/romp_gps
spring.mongodb.database=romp_gps
spring.data.mongodb.auto-index-creation=true